// export const FETCH_DATA = "FETCH_DATA";

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const UPDATE_ORDERS = 'UPDATE_ORDERS';

export const FILTER_VALUE = 'FILTER_VALUE';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';


export const GET_RECORDS_START = 'GET_RECORDS_START';
export const GET_RECORDS_FAIL = 'GET_RECORDS_FAIL';
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const GET_CONTACTED_START = 'GET_CONTACTED_START';
export const GET_CONTACTED_FAIL = 'GET_CONTACTED_FAIL';
export const GET_CONTACTED_SUCCESS = 'GET_CONTACTED_SUCCESS';
export const GET_UNCONTACTED_START = 'GET_UNCONTACTED_START';
export const GET_UNCONTACTED_FAIL = 'GET_UNCONTACTED_FAIL';
export const GET_UNCONTACTED_SUCCESS = 'GET_UNCONTACTED_SUCCESS';
export const GET_INFO = 'GET_INFO';
export const GET_ADD_RECORDS = 'GET_ADD_RECORDS';
